stages:
  - train
  - build
  - deploy

variables:
  IMAGE_NAME: "YOUR PATH TO IMAGE"
  VM_USER: "YUOR USER"

train_model:
  stage: train
  image: python:3.9
  script:
    - pip install -r service_model/requirements.txt
    - python service_model/train.py
  artifacts:
    paths:
      - service_model/full_model_pipeline.joblib
      - mlruns/
    expire_in: 1 week

build_web:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - cat $YC_KEY_JSON | docker login --username json_key --password-stdin cr.yandex
    - docker build -t $IMAGE_NAME -f service_web/Dockerfile .
    - docker push $IMAGE_NAME

deploy_to_vm:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "" >> $ID_ED25519
    - chmod 400 $ID_ED25519
    - ssh-add $ID_ED25519
  script:
    - scp -o StrictHostKeyChecking=no $YC_KEY_JSON $VM_USER@$VM_IP:/tmp/key.json
    - ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "cat /tmp/key.json | docker login --username json_key --password-stdin cr.yandex && docker pull $IMAGE_NAME && docker stop web-app || true && docker rm web-app || true && docker run -d --name web-app -p 80:80 $IMAGE_NAME"